### ISSUE TITLE
Could you give me your Email

### ISSUE THREAD

**Issue by williamze** [James-Oswald/Wireshrek#1]
Hello I‘m very interested in this project. Could you give me your Email

**Comment by James-Oswald** [comment]
Feel free to reach out to me at jtoswald@albany.edu with any questions.

I don't really have any big plans for this project, its basically done. scapy's sniffing uses too much CPU for it to be practical to leave on in the background. You're welcome to fork it and edit the code as you see fit, ill add a license.
